# How to build dockerfile if name is not Dockerfile or Dockerfile?
# docker build
# docker build -f <docker-file-name> <path-to-context>
# docker build -t tnn4/poke-rs-api:0.1.0 -f <dockerfile-name> <path-to-context>
# path-to-context is usually . , the current working directory

# COPY only supports the basic copying of local files into the container, 
# while ADD has some features 
# (like local-only tar extraction and remote URL support) that are not immediately obvious. 

# Build the backend
# FROM alpine:3.17.3 as builder
FROM rust:1.67
WORKDIR /home/t/src/myapp
# COPY HOST_PATH DST_PATH
COPY . .
RUN apt-get update && apt-get upgrade -y
RUN apt-get install libssl-dev
RUN apt-get install -y -q build-essential curl
# RUN cargo install --path poke-rs-api

FROM debian:bullseye-slim
# RUN apt-get update && apt-get install -y <extra-runtime-dependencies> && rm -rf /var/lib/apt/lists/*
# RUN apt-get update && apt-get install -y && rm -rf /var/lib/apt/lists/*
# COPY --from=builder /usr/local/cargo/bin/poke-rs-api /usr/local/bin/poke-rs-api
# CMD ["poke-rs-api"]

CMD ["bin/poke-rs-api"]