# You should only use this if you intend to build the binary from scratch, otherwise use `Dockerfile` which just uses the pre-built binary.

# How to build dockerfile if name is not Dockerfile or Dockerfile?
# docker build
# docker build -f <docker-file-name> <path-to-context>
# path-to-context is usually . , the current working directory

# COPY only supports the basic copying of local files into the container, 
# while ADD has some features 
# (like local-only tar extraction and remote URL support) that are not immediately obvious. 

# Build the backend
FROM rust:1.67 as builder
WORKDIR /usr/src/myapp
# COPY HOST_PATH DST_PATH
COPY . .
RUN cargo install --path poke-rs-api

FROM debian:bullseye-slim
# RUN apt-get update && apt-get install -y <extra-runtime-dependencies> && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y && rm -rf /var/lib/apt/lists/*
# COPY --from=builder /usr/local/cargo/bin/poke-rs-api /usr/local/bin/poke-rs-api
COPY --from=builder /usr/local/cargo/bin/poke-rs-api /usr/local/bin/poke-rs-api
CMD ["poke-rs-api"]