cheri=1
chesto=2
pecha=3
rawst=4
aspear=5
leppa=6
oran=7
persim=8
lum=9
sitrus=10
figy=11
wiki=12
mago=13
aguav=14
iapapa=15
razz=16
bluk=17
nanab=18
wepear=19
pinap=20
pomeg=21
kelpsy=22
qualot=23
hondew=24
grepa=25
tamato=26
cornn=27
magost=28
rabuta=29
nomel=30
spelon=31
pamtre=32
watmel=33
durin=34
belue=35
occa=36
passho=37
wacan=38
rindo=39
yache=40
chople=41
kebia=42
shuca=43
coba=44
payapa=45
tanga=46
charti=47
kasib=48
haban=49
colbur=50
babiri=51
chilan=52
liechi=53
ganlon=54
salac=55
petaya=56
apicot=57
lansat=58
starf=59
enigma=60
micle=61
custap=62
jaboca=63
rowap=64
