pound=1
karate-chop=2
double-slap=3
comet-punch=4
mega-punch=5
pay-day=6
fire-punch=7
ice-punch=8
thunder-punch=9
scratch=10
vice-grip=11
guillotine=12
razor-wind=13
swords-dance=14
cut=15
gust=16
wing-attack=17
whirlwind=18
fly=19
bind=20
slam=21
vine-whip=22
stomp=23
double-kick=24
mega-kick=25
jump-kick=26
rolling-kick=27
sand-attack=28
headbutt=29
horn-attack=30
fury-attack=31
horn-drill=32
tackle=33
body-slam=34
wrap=35
take-down=36
thrash=37
double-edge=38
tail-whip=39
poison-sting=40
twineedle=41
pin-missile=42
leer=43
bite=44
growl=45
roar=46
sing=47
supersonic=48
sonic-boom=49
disable=50
acid=51
ember=52
flamethrower=53
mist=54
water-gun=55
hydro-pump=56
surf=57
ice-beam=58
blizzard=59
psybeam=60
bubble-beam=61
aurora-beam=62
hyper-beam=63
peck=64
drill-peck=65
submission=66
low-kick=67
counter=68
seismic-toss=69
strength=70
absorb=71
mega-drain=72
leech-seed=73
growth=74
razor-leaf=75
solar-beam=76
poison-powder=77
stun-spore=78
sleep-powder=79
petal-dance=80
string-shot=81
dragon-rage=82
fire-spin=83
thunder-shock=84
thunderbolt=85
thunder-wave=86
thunder=87
rock-throw=88
earthquake=89
fissure=90
dig=91
toxic=92
confusion=93
psychic=94
hypnosis=95
meditate=96
agility=97
quick-attack=98
rage=99
teleport=100
night-shade=101
mimic=102
screech=103
double-team=104
recover=105
harden=106
minimize=107
smokescreen=108
confuse-ray=109
withdraw=110
defense-curl=111
barrier=112
light-screen=113
haze=114
reflect=115
focus-energy=116
bide=117
metronome=118
mirror-move=119
self-destruct=120
egg-bomb=121
lick=122
smog=123
sludge=124
bone-club=125
fire-blast=126
waterfall=127
clamp=128
swift=129
skull-bash=130
spike-cannon=131
constrict=132
amnesia=133
kinesis=134
soft-boiled=135
high-jump-kick=136
glare=137
dream-eater=138
poison-gas=139
barrage=140
leech-life=141
lovely-kiss=142
sky-attack=143
transform=144
bubble=145
dizzy-punch=146
spore=147
flash=148
psywave=149
splash=150
acid-armor=151
crabhammer=152
explosion=153
fury-swipes=154
bonemerang=155
rest=156
rock-slide=157
hyper-fang=158
sharpen=159
conversion=160
tri-attack=161
super-fang=162
slash=163
substitute=164
struggle=165
sketch=166
triple-kick=167
thief=168
spider-web=169
mind-reader=170
nightmare=171
flame-wheel=172
snore=173
curse=174
flail=175
conversion-2=176
aeroblast=177
cotton-spore=178
reversal=179
spite=180
powder-snow=181
protect=182
mach-punch=183
scary-face=184
feint-attack=185
sweet-kiss=186
belly-drum=187
sludge-bomb=188
mud-slap=189
octazooka=190
spikes=191
zap-cannon=192
foresight=193
destiny-bond=194
perish-song=195
icy-wind=196
detect=197
bone-rush=198
lock-on=199
outrage=200
sandstorm=201
giga-drain=202
endure=203
charm=204
rollout=205
false-swipe=206
swagger=207
milk-drink=208
spark=209
fury-cutter=210
steel-wing=211
mean-look=212
attract=213
sleep-talk=214
heal-bell=215
return=216
present=217
frustration=218
safeguard=219
pain-split=220
sacred-fire=221
magnitude=222
dynamic-punch=223
megahorn=224
dragon-breath=225
baton-pass=226
encore=227
pursuit=228
rapid-spin=229
sweet-scent=230
iron-tail=231
metal-claw=232
vital-throw=233
morning-sun=234
synthesis=235
moonlight=236
hidden-power=237
cross-chop=238
twister=239
rain-dance=240
sunny-day=241
crunch=242
mirror-coat=243
psych-up=244
extreme-speed=245
ancient-power=246
shadow-ball=247
future-sight=248
rock-smash=249
whirlpool=250
beat-up=251
fake-out=252
uproar=253
stockpile=254
spit-up=255
swallow=256
heat-wave=257
hail=258
torment=259
flatter=260
will-o-wisp=261
memento=262
facade=263
focus-punch=264
smelling-salts=265
follow-me=266
nature-power=267
charge=268
taunt=269
helping-hand=270
trick=271
role-play=272
wish=273
assist=274
ingrain=275
superpower=276
magic-coat=277
recycle=278
revenge=279
brick-break=280
yawn=281
knock-off=282
endeavor=283
eruption=284
skill-swap=285
imprison=286
refresh=287
grudge=288
snatch=289
secret-power=290
dive=291
arm-thrust=292
camouflage=293
tail-glow=294
luster-purge=295
mist-ball=296
feather-dance=297
teeter-dance=298
blaze-kick=299
mud-sport=300
ice-ball=301
needle-arm=302
slack-off=303
hyper-voice=304
poison-fang=305
crush-claw=306
blast-burn=307
hydro-cannon=308
meteor-mash=309
astonish=310
weather-ball=311
aromatherapy=312
fake-tears=313
air-cutter=314
overheat=315
odor-sleuth=316
rock-tomb=317
silver-wind=318
metal-sound=319
grass-whistle=320
tickle=321
cosmic-power=322
water-spout=323
signal-beam=324
shadow-punch=325
extrasensory=326
sky-uppercut=327
sand-tomb=328
sheer-cold=329
muddy-water=330
bullet-seed=331
aerial-ace=332
icicle-spear=333
iron-defense=334
block=335
howl=336
dragon-claw=337
frenzy-plant=338
bulk-up=339
bounce=340
mud-shot=341
poison-tail=342
covet=343
volt-tackle=344
magical-leaf=345
water-sport=346
calm-mind=347
leaf-blade=348
dragon-dance=349
rock-blast=350
shock-wave=351
water-pulse=352
doom-desire=353
psycho-boost=354
roost=355
gravity=356
miracle-eye=357
wake-up-slap=358
hammer-arm=359
gyro-ball=360
healing-wish=361
brine=362
natural-gift=363
feint=364
pluck=365
tailwind=366
acupressure=367
metal-burst=368
u-turn=369
close-combat=370
payback=371
assurance=372
embargo=373
fling=374
psycho-shift=375
trump-card=376
heal-block=377
wring-out=378
power-trick=379
gastro-acid=380
lucky-chant=381
me-first=382
copycat=383
power-swap=384
guard-swap=385
punishment=386
last-resort=387
worry-seed=388
sucker-punch=389
toxic-spikes=390
heart-swap=391
aqua-ring=392
magnet-rise=393
flare-blitz=394
force-palm=395
aura-sphere=396
rock-polish=397
poison-jab=398
dark-pulse=399
night-slash=400
aqua-tail=401
seed-bomb=402
air-slash=403
x-scissor=404
bug-buzz=405
dragon-pulse=406
dragon-rush=407
power-gem=408
drain-punch=409
vacuum-wave=410
focus-blast=411
energy-ball=412
brave-bird=413
earth-power=414
switcheroo=415
giga-impact=416
nasty-plot=417
bullet-punch=418
avalanche=419
ice-shard=420
shadow-claw=421
thunder-fang=422
ice-fang=423
fire-fang=424
shadow-sneak=425
mud-bomb=426
psycho-cut=427
zen-headbutt=428
mirror-shot=429
flash-cannon=430
rock-climb=431
defog=432
trick-room=433
draco-meteor=434
discharge=435
lava-plume=436
leaf-storm=437
power-whip=438
rock-wrecker=439
cross-poison=440
gunk-shot=441
iron-head=442
magnet-bomb=443
stone-edge=444
captivate=445
stealth-rock=446
grass-knot=447
chatter=448
judgment=449
bug-bite=450
charge-beam=451
wood-hammer=452
aqua-jet=453
attack-order=454
defend-order=455
heal-order=456
head-smash=457
double-hit=458
roar-of-time=459
spacial-rend=460
lunar-dance=461
crush-grip=462
magma-storm=463
dark-void=464
seed-flare=465
ominous-wind=466
shadow-force=467
hone-claws=468
wide-guard=469
guard-split=470
power-split=471
wonder-room=472
psyshock=473
venoshock=474
autotomize=475
rage-powder=476
telekinesis=477
magic-room=478
smack-down=479
storm-throw=480
flame-burst=481
sludge-wave=482
quiver-dance=483
heavy-slam=484
synchronoise=485
electro-ball=486
soak=487
flame-charge=488
coil=489
low-sweep=490
acid-spray=491
foul-play=492
simple-beam=493
entrainment=494
after-you=495
round=496
echoed-voice=497
chip-away=498
clear-smog=499
stored-power=500
quick-guard=501
ally-switch=502
scald=503
shell-smash=504
heal-pulse=505
hex=506
sky-drop=507
shift-gear=508
circle-throw=509
incinerate=510
quash=511
acrobatics=512
reflect-type=513
retaliate=514
final-gambit=515
bestow=516
inferno=517
water-pledge=518
fire-pledge=519
grass-pledge=520
volt-switch=521
struggle-bug=522
bulldoze=523
frost-breath=524
dragon-tail=525
work-up=526
electroweb=527
wild-charge=528
drill-run=529
dual-chop=530
heart-stamp=531
horn-leech=532
sacred-sword=533
razor-shell=534
heat-crash=535
leaf-tornado=536
steamroller=537
cotton-guard=538
night-daze=539
psystrike=540
tail-slap=541
hurricane=542
head-charge=543
gear-grind=544
searing-shot=545
techno-blast=546
relic-song=547
secret-sword=548
glaciate=549
bolt-strike=550
blue-flare=551
fiery-dance=552
freeze-shock=553
ice-burn=554
snarl=555
icicle-crash=556
v-create=557
fusion-flare=558
fusion-bolt=559
flying-press=560
mat-block=561
belch=562
rototiller=563
sticky-web=564
fell-stinger=565
phantom-force=566
trick-or-treat=567
noble-roar=568
ion-deluge=569
parabolic-charge=570
forests-curse=571
petal-blizzard=572
freeze-dry=573
disarming-voice=574
parting-shot=575
topsy-turvy=576
draining-kiss=577
crafty-shield=578
flower-shield=579
grassy-terrain=580
misty-terrain=581
electrify=582
play-rough=583
fairy-wind=584
moonblast=585
boomburst=586
fairy-lock=587
kings-shield=588
play-nice=589
confide=590
diamond-storm=591
steam-eruption=592
hyperspace-hole=593
water-shuriken=594
mystical-fire=595
spiky-shield=596
aromatic-mist=597
eerie-impulse=598
venom-drench=599
powder=600
geomancy=601
magnetic-flux=602
happy-hour=603
electric-terrain=604
dazzling-gleam=605
celebrate=606
hold-hands=607
baby-doll-eyes=608
nuzzle=609
hold-back=610
infestation=611
power-up-punch=612
oblivion-wing=613
thousand-arrows=614
thousand-waves=615
lands-wrath=616
light-of-ruin=617
origin-pulse=618
precipice-blades=619
dragon-ascent=620
hyperspace-fury=621
breakneck-blitz--physical=622
breakneck-blitz--special=623
all-out-pummeling--physical=624
all-out-pummeling--special=625
supersonic-skystrike--physical=626
supersonic-skystrike--special=627
acid-downpour--physical=628
acid-downpour--special=629
tectonic-rage--physical=630
tectonic-rage--special=631
continental-crush--physical=632
continental-crush--special=633
savage-spin-out--physical=634
savage-spin-out--special=635
never-ending-nightmare--physical=636
never-ending-nightmare--special=637
corkscrew-crash--physical=638
corkscrew-crash--special=639
inferno-overdrive--physical=640
inferno-overdrive--special=641
hydro-vortex--physical=642
hydro-vortex--special=643
bloom-doom--physical=644
bloom-doom--special=645
gigavolt-havoc--physical=646
gigavolt-havoc--special=647
shattered-psyche--physical=648
shattered-psyche--special=649
subzero-slammer--physical=650
subzero-slammer--special=651
devastating-drake--physical=652
devastating-drake--special=653
black-hole-eclipse--physical=654
black-hole-eclipse--special=655
twinkle-tackle--physical=656
twinkle-tackle--special=657
catastropika=658
shore-up=659
first-impression=660
baneful-bunker=661
spirit-shackle=662
darkest-lariat=663
sparkling-aria=664
ice-hammer=665
floral-healing=666
high-horsepower=667
strength-sap=668
solar-blade=669
leafage=670
spotlight=671
toxic-thread=672
laser-focus=673
gear-up=674
throat-chop=675
pollen-puff=676
anchor-shot=677
psychic-terrain=678
lunge=679
fire-lash=680
power-trip=681
burn-up=682
speed-swap=683
smart-strike=684
purify=685
revelation-dance=686
core-enforcer=687
trop-kick=688
instruct=689
beak-blast=690
clanging-scales=691
dragon-hammer=692
brutal-swing=693
aurora-veil=694
sinister-arrow-raid=695
malicious-moonsault=696
oceanic-operetta=697
guardian-of-alola=698
soul-stealing-7-star-strike=699
stoked-sparksurfer=700
pulverizing-pancake=701
extreme-evoboost=702
genesis-supernova=703
shell-trap=704
fleur-cannon=705
psychic-fangs=706
stomping-tantrum=707
shadow-bone=708
accelerock=709
liquidation=710
prismatic-laser=711
spectral-thief=712
sunsteel-strike=713
moongeist-beam=714
tearful-look=715
zing-zap=716
natures-madness=717
multi-attack=718
10-000-000-volt-thunderbolt=719
mind-blown=720
plasma-fists=721
photon-geyser=722
light-that-burns-the-sky=723
searing-sunraze-smash=724
menacing-moonraze-maelstrom=725
lets-snuggle-forever=726
splintered-stormshards=727
clangorous-soulblaze=728
zippy-zap=729
splishy-splash=730
floaty-fall=731
pika-papow=732
bouncy-bubble=733
buzzy-buzz=734
sizzly-slide=735
glitzy-glow=736
baddy-bad=737
sappy-seed=738
freezy-frost=739
sparkly-swirl=740
veevee-volley=741
double-iron-bash=742
max-guard=743
dynamax-cannon=744
snipe-shot=745
jaw-lock=746
stuff-cheeks=747
no-retreat=748
tar-shot=749
magic-powder=750
dragon-darts=751
teatime=752
octolock=753
bolt-beak=754
fishious-rend=755
court-change=756
max-flare=757
max-flutterby=758
max-lightning=759
max-strike=760
max-knuckle=761
max-phantasm=762
max-hailstorm=763
max-ooze=764
max-geyser=765
max-airstream=766
max-starfall=767
max-wyrmwind=768
max-mindstorm=769
max-rockfall=770
max-quake=771
max-darkness=772
max-overgrowth=773
max-steelspike=774
clangorous-soul=775
body-press=776
decorate=777
drum-beating=778
snap-trap=779
pyro-ball=780
behemoth-blade=781
behemoth-bash=782
aura-wheel=783
breaking-swipe=784
branch-poke=785
overdrive=786
apple-acid=787
grav-apple=788
spirit-break=789
strange-steam=790
life-dew=791
obstruct=792
false-surrender=793
meteor-assault=794
eternabeam=795
steel-beam=796
expanding-force=797
steel-roller=798
scale-shot=799
meteor-beam=800
shell-side-arm=801
misty-explosion=802
grassy-glide=803
rising-voltage=804
terrain-pulse=805
skitter-smack=806
burning-jealousy=807
lash-out=808
poltergeist=809
corrosive-gas=810
coaching=811
flip-turn=812
triple-axel=813
dual-wingbeat=814
scorching-sands=815
jungle-healing=816
wicked-blow=817
surging-strikes=818
thunder-cage=819
dragon-energy=820
freezing-glare=821
fiery-wrath=822
thunderous-kick=823
glacial-lance=824
astral-barrage=825
eerie-spell=826
dire-claw=827
psyshield-bash=828
power-shift=829
stone-axe=830
springtide-storm=831
mystical-power=832
raging-fury=833
wave-crash=834
chloroblast=835
mountain-gale=836
victory-dance=837
headlong-rush=838
barb-barrage=839
esper-wing=840
bitter-malice=841
shelter=842
triple-arrows=843
infernal-parade=844
ceaseless-edge=845
bleakwind-storm=846
wildbolt-storm=847
sandsear-storm=848
lunar-blessing=849
take-heart=850
tera-blast=851
silk-trap=852
axe-kick=853
last-respects=854
lumina-crash=855
order-up=856
jet-punch=857
spicy-extract=858
spin-out=859
population-bomb=860
ice-spinner=861
glaive-rush=862
revival-blessing=863
salt-cure=864
triple-dive=865
mortal-spin=866
doodle=867
fillet-away=868
kowtow-cleave=869
flower-trick=870
torch-song=871
aqua-step=872
raging-bull=873
make-it-rain=874
ruination=877
collision-course=878
electro-drift=879
shed-tail=880
chilly-reception=881
tidy-up=882
snowscape=883
pounce=884
trailblaze=885
chilling-water=886
hyper-drill=887
twin-beam=888
rage-fist=889
armor-cannon=890
bitter-blade=891
double-shock=892
gigaton-hammer=893
comeuppance=894
aqua-cutter=895
blazing-torque=896
wicked-torque=897
noxious-torque=898
combat-torque=899
magical-torque=900
hydro-steam=901
psyblade=902
